"use client";
import "../styles/globals.css";
import { Montserrat } from "next/font/google";
import SeshProvider from "@/components/SeshProvider";
import NavBar from "@/components/NavBar";
import { Provider } from "react-redux";
import { store } from "@/store";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <SeshProvider>
        <html lang="en">
          <body className={`${montserrat.className} bg-[#121212]`}>
            <NavBar />
            {children}
          </body>
        </html>
      </SeshProvider>
    </Provider>
  );
}
